name: release

on:
  push:
    branches:
      - main
      - next

jobs:
  build:
    if: ${{ github.repository_owner == 'beeman' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm run publish
          commit: '[ci] release'
          title: '[ci] release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
